import type { Fixture } from '../types.js';

// FIFA World Cup 2026 — Group Stage Featured Fixtures
// Tournament opens: June 11, 2026 | Host: USA, Canada, Mexico
export const FIXTURES: Fixture[] = [
  {
    id: 'grp-a-1',
    matchday: 1,
    group: 'A',
    home: { name: 'Mexico', code: 'MEX', flag: '🇲🇽' },
    away: { name: 'Croatia', code: 'CRO', flag: '🇭🇷' },
    kickoff: '2026-06-11T20:00:00Z',
    venue: 'AT&T Stadium · Dallas',
    status: 'open',
  },
  {
    id: 'grp-a-2',
    matchday: 1,
    group: 'A',
    home: { name: 'Belgium', code: 'BEL', flag: '🇧🇪' },
    away: { name: 'Morocco', code: 'MAR', flag: '🇲🇦' },
    kickoff: '2026-06-11T23:00:00Z',
    venue: "Levi's Stadium · San Francisco",
    status: 'open',
  },
  {
    id: 'grp-b-1',
    matchday: 1,
    group: 'B',
    home: { name: 'Brazil', code: 'BRA', flag: '🇧🇷' },
    away: { name: 'Germany', code: 'GER', flag: '🇩🇪' },
    kickoff: '2026-06-12T17:00:00Z',
    venue: 'MetLife Stadium · New York',
    status: 'open',
  },
  {
    id: 'grp-b-2',
    matchday: 1,
    group: 'B',
    home: { name: 'Switzerland', code: 'SUI', flag: '🇨🇭' },
    away: { name: 'Canada', code: 'CAN', flag: '🇨🇦' },
    kickoff: '2026-06-12T20:00:00Z',
    venue: 'Gillette Stadium · Boston',
    status: 'open',
  },
  {
    id: 'grp-c-1',
    matchday: 1,
    group: 'C',
    home: { name: 'France', code: 'FRA', flag: '🇫🇷' },
    away: { name: 'Australia', code: 'AUS', flag: '🇦🇺' },
    kickoff: '2026-06-13T17:00:00Z',
    venue: 'SoFi Stadium · Los Angeles',
    status: 'open',
  },
  {
    id: 'grp-d-1',
    matchday: 1,
    group: 'D',
    home: { name: 'England', code: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
    away: { name: 'Spain', code: 'ESP', flag: '🇪🇸' },
    kickoff: '2026-06-13T20:00:00Z',
    venue: 'Rose Bowl · Los Angeles',
    status: 'open',
  },
  {
    id: 'grp-e-1',
    matchday: 1,
    group: 'E',
    home: { name: 'Argentina', code: 'ARG', flag: '🇦🇷' },
    away: { name: 'France', code: 'FRA', flag: '🇫🇷' },
    kickoff: '2026-06-14T17:00:00Z',
    venue: 'Arrowhead Stadium · Kansas City',
    status: 'open',
  },
  {
    id: 'grp-f-1',
    matchday: 1,
    group: 'F',
    home: { name: 'Portugal', code: 'POR', flag: '🇵🇹' },
    away: { name: 'Morocco', code: 'MAR', flag: '🇲🇦' },
    kickoff: '2026-06-15T17:00:00Z',
    venue: 'Lumen Field · Seattle',
    status: 'open',
  },
  {
    id: 'grp-g-1',
    matchday: 1,
    group: 'G',
    home: { name: 'USA', code: 'USA', flag: '🇺🇸' },
    away: { name: 'Netherlands', code: 'NED', flag: '🇳🇱' },
    kickoff: '2026-06-15T20:00:00Z',
    venue: 'SoFi Stadium · Los Angeles',
    status: 'open',
  },
  {
    id: 'grp-h-1',
    matchday: 1,
    group: 'H',
    home: { name: 'Senegal', code: 'SEN', flag: '🇸🇳' },
    away: { name: 'Nigeria', code: 'NGA', flag: '🇳🇬' },
    kickoff: '2026-06-16T17:00:00Z',
    venue: 'AT&T Stadium · Dallas',
    status: 'open',
  },
];

export function getFixture(id: string): Fixture | undefined {
  return FIXTURES.find((f) => f.id === id);
}
